apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: course-app
  namespace: default
spec:
  interval: 5m
  url: https://github.com/VadymKhvoinytskyi/rd-fluxcd-lesson
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: course-app-dev
  namespace: flux-dev
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: rd-fluxcd-lesson
  path: ".overlays/dev/"
  prune: true
  timeout: 1m
