resources:
- ../../base
namespace: production

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: course-app


configMapGenerator:
- name: test-config
  behavior: merge
  files:
  -  application.properties
